
import { Ebook, ComplexityRating } from './types';

export const ALL_EBOOKS: Ebook[] = [
  {
    id: '1',
    title: 'AI Agents in Practice',
    description: 'A comprehensive guide to building and deploying autonomous AI agents for real-world applications.',
    author: 'Dr. Evelyn Reed',
    price: 3999,
    coverUrl: 'https://picsum.photos/seed/ai-agents/400/600',
    category: 'AI/ML',
    complexity: ComplexityRating.Advanced,
    frameworkTags: ['LangChain', 'Python', 'API'],
    pageCount: 320,
  },
  {
    id: '2',
    title: 'Product Design for Tech Leaders',
    description: 'Master the principles of user-centric design to build products that users love and drive business success.',
    author: 'Leo Chen',
    price: 2999,
    coverUrl: 'https://picsum.photos/seed/product-design/400/600',
    category: 'Product Design',
    complexity: ComplexityRating.Intermediate,
    frameworkTags: ['Figma', 'UX/UI', 'Agile'],
    pageCount: 250,
  },
  {
    id: '3',
    title: 'The AI Startup Playbook',
    description: 'From idea to IPO, this book covers everything you need to know about building a successful AI startup.',
    author: 'Jian Yang',
    price: 4500,
    coverUrl: 'https://picsum.photos/seed/ai-startup/400/600',
    category: 'Tech AI Startups',
    complexity: ComplexityRating.Intermediate,
    frameworkTags: ['Venture Capital', 'Growth Hacking', 'SaaS'],
    pageCount: 410,
  },
  {
    id: '4',
    title: 'Managing AI Products',
    description: 'A product manager\'s guide to the unique challenges and opportunities of the AI product lifecycle.',
    author: 'Sofia Alvarez',
    price: 3499,
    coverUrl: 'https://picsum.photos/seed/ai-pm/400/600',
    category: 'Product Management',
    complexity: ComplexityRating.Intermediate,
    frameworkTags: ['Roadmapping', 'A/B Testing', 'Data Science'],
    pageCount: 280,
  },
  {
    id: '5',
    title: 'Advanced Prompt Engineering',
    description: 'Unlock the full potential of large language models with advanced prompt engineering techniques.',
    author: 'Ben Carter',
    price: 4999,
    coverUrl: 'https://picsum.photos/seed/prompt-eng/400/600',
    category: 'AI/ML',
    complexity: ComplexityRating.Advanced,
    frameworkTags: ['LLM', 'GPT-4', 'Optimization'],
    pageCount: 190,
  },
  {
    id: '6',
    title: 'Decoding Tech Platforms',
    description: 'An insider look at the architecture and business models of the world\'s most successful tech platforms.',
    author: 'Maria Schmidt',
    price: 3200,
    coverUrl: 'https://picsum.photos/seed/tech-platforms/400/600',
    category: 'Tech Platforms',
    complexity: ComplexityRating.Research,
    frameworkTags: ['Scalability', 'APIs', 'Network Effects'],
    pageCount: 550,
  },
   {
    id: '7',
    title: 'Introduction to Neural Networks',
    description: 'A beginner-friendly introduction to the core concepts of neural networks and deep learning.',
    author: 'Alice Johnson',
    price: 1999,
    coverUrl: 'https://picsum.photos/seed/neural-nets/400/600',
    category: 'AI/ML',
    complexity: ComplexityRating.Beginner,
    frameworkTags: ['Python', 'TensorFlow', 'Keras'],
    pageCount: 180,
  },
  {
    id: '8',
    title: 'Data-Driven Product Management',
    description: 'Learn how to leverage data to make informed product decisions and drive growth.',
    author: 'David Kim',
    price: 3599,
    coverUrl: 'https://picsum.photos/seed/data-pm/400/600',
    category: 'Product Management',
    complexity: ComplexityRating.Intermediate,
    frameworkTags: ['SQL', 'Analytics', 'Metrics'],
    pageCount: 300,
  }
];
